version: '3.9'

networks:
  auth-network:

services:
  mongo:
    image: mongo:5.0.0
    environment:
      - MONGO_URL=mongodb://mongo:27017/auth-backend-test
    ports:
      - 27017:27017
    networks:
      - auth-network

  rabbitmq:
    image: 'rabbitmq:3.8-management'
    volumes:
      - './.docker/conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf'
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - auth-network

  s3-storage:
    image: localstack/localstack:0.12.5
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DISABLE_CORS_CHECKS=1
      - DISABLE_CUSTOM_CORS_S3=1
    ports:
      - 4566:4566
    volumes:
      - './.docker/conf/s3/.init:/docker-entrypoint-initaws.d'
      - './.docker/conf/s3/.localstack:/tmp/localstack'
